name: 'Get & cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('custom-actions/**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        cd custom-actions
        npm ci
      shell: bash